#*Dataframe / pd example
#df.sort_values 
#df.groupby
#

In [27]:
import pandas as pd
import numpy as np
pd.read_excel('stud_db.xlsx')

   Roll Name  Marks Address  Dept
0     1   qw     76    Pune     1
1     2   df     45  Mumbai     1
2     3   vc     56  Nagpur     1
3     4   bn     78    Pune     2
4     5   hj     74  Mumbai     2
5     6   yu     49  Nagpur     2
6     7   fg     68    Pune     2
7     8   tr     84  Mumbai     1

In [2]:
df_students = pd.read_excel('stud_db.xlsx', sheet_name='XII')
df_depts = pd.read_excel('stud_db.xlsx',sheet_name='Depts')

In [3]:
df_depts

   dept_id          Name  HOD
0        1  Comp Science  XYZ
1        2    Statistics  PQR
2        3         Maths  MNO

In [4]:
#What is the name of student who got highest marks in Statistics department?
dept_no = df_depts[df_depts['Name']== 'Statistics']['dept_id'].iloc[0] 
df_statistics = df_students[df_students['Dept']==2]
df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

C:\Users\niraj\AppData\Local\Temp\ipykernel_7400\3438441322.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

'bn'

In [7]:
#Merge the two dataframes
df_merged = pd.merge(left=df_students, right=df_depts, left_on='Dept', right_on='dept_id')

In [8]:
df_merged

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

In [11]:
df_statistics = df_students[df_students['Dept']==2]

df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

C:\Users\niraj\AppData\Local\Temp\ipykernel_7400\4138169399.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

'bn'

In [17]:
df_merged[df_merged['Marks']==df_merged['Marks'].max()]['HOD'].iloc[0]

'XYZ'

In [20]:
df_statistics = df_students[df_students['Dept']==2]
df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

C:\Users\niraj\AppData\Local\Temp\ipykernel_7400\2740854775.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_statistics[df_students['Marks']==df_statistics['Marks'].max()]['Name'].iloc[0]

'bn'

In [21]:
df_merged

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

# Types of Joins in SQL

## 1. Inner Join
# Only records with matching values in both tables are included.

## 2. Left Join (Left Outer Join)
# Includes **all records** from the left table and only the **matching records** from the right table.

## 3. Right Join (Right Outer Join)
# Includes **all records** from the right table and only the **matching records** from the left table.

## 4. Full Outer Join
# Includes **all records** from both tables, with matches where available. Unmatched rows are filled with NULLs.

In [24]:
#Inner join
df_inner = pd.merge(left=df_students, right=df_depts, left_on='Dept', right_on='dept_id', how='inner')
df_inner

   Roll Name_x  Marks Address  Dept  dept_id        Name_y  HOD
0     1     qw     76    Pune     1        1  Comp Science  XYZ
1     2     df     45  Mumbai     1        1  Comp Science  XYZ
2     3     vc     56  Nagpur     1        1  Comp Science  XYZ
3     4     bn     78    Pune     2        2    Statistics  PQR
4     5     hj     74  Mumbai     2        2    Statistics  PQR
5     6     yu     49  Nagpur     2        2    Statistics  PQR
6     7     fg     68    Pune     2        2    Statistics  PQR
7     8     tr     84  Mumbai     1        1  Comp Science  XYZ

#Concatnation function

In [30]:
df1= pd.DataFrame(data = np.random.rand(4,3),columns =['Roll', 'Name', 'Marks' ])
df2= pd.DataFrame(data = np.random.rand(3,3),columns=['Roll', 'Name', 'Marks' ])
df3= pd.DataFrame(data = np.random.rand(4,2),columns=['Email', 'Mobile'])

In [31]:
df1,df2,df3

(       Roll      Name     Marks
 0  0.661612  0.972235  0.653135
 1  0.654494  0.772518  0.844294
 2  0.741942  0.565733  0.949254
 3  0.877995  0.978348  0.867704,
        Roll      Name     Marks
 0  0.258906  0.375389  0.300490
 1  0.060928  0.685569  0.180659
 2  0.164439  0.364411  0.780558,
       Email    Mobile
 0  0.650535  0.163967
 1  0.873352  0.607029
 2  0.683004  0.816413
 3  0.709912  0.280911)

In [33]:
pd.concat([df1,df3],axis=1)

       Roll      Name     Marks     Email    Mobile
0  0.661612  0.972235  0.653135  0.650535  0.163967
1  0.654494  0.772518  0.844294  0.873352  0.607029
2  0.741942  0.565733  0.949254  0.683004  0.816413
3  0.877995  0.978348  0.867704  0.709912  0.280911

Homework
df.pivot(In excel)